    animations = (

        {
            triggers = ["close", "hide"];
            preset = "fly-out";
            direction = "down";
            duration = 0.2;
        },

        {
            triggers = ["open", "show"];
            preset = "fly-in";
            direction = "down";
            duration = 0.2;
        }
    )
